# NumPy Basics - Foundation for Machine Learning

NumPy is the fundamental package for numerical computing in Python.
Understanding NumPy is crucial for ML as most libraries build on top of it.

In [1]:
import numpy as np

## 1. Creating Arrays

In [2]:
# Create arrays from lists
arr1d = np.array([1, 2, 3, 4, 5])
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

print(f"1D Array: {arr1d}")
print(f"2D Array:\n{arr2d}")
print(f"Shape of 2D array: {arr2d.shape}")
print(f"Data type: {arr2d.dtype}\n")

1D Array: [1 2 3 4 5]
2D Array:
[[1 2 3]
 [4 5 6]]
Shape of 2D array: (2, 3)
Data type: int64



In [3]:
# Special arrays
zeros = np.zeros((3, 3))
ones = np.ones((2, 4))
identity = np.eye(3)
random_arr = np.random.rand(3, 3)

print(f"Zeros:\n{zeros}\n")
print(f"Ones:\n{ones}\n")
print(f"Identity:\n{identity}\n")
print(f"Random:\n{random_arr}\n")

Zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Identity:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random:
[[0.9700248  0.606123   0.61038395]
 [0.32874066 0.36453604 0.96506234]
 [0.33633329 0.84794819 0.96028606]]



## 2. Array Operations

In [4]:
# Element-wise operations
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print(f"a = {a}")
print(f"b = {b}")
print(f"a + b = {a + b}")
print(f"a * b = {a * b}")
print(f"a ** 2 = {a ** 2}")
print(f"Square root of b: {np.sqrt(b)}\n")

a = [1 2 3 4]
b = [10 20 30 40]
a + b = [11 22 33 44]
a * b = [ 10  40  90 160]
a ** 2 = [ 1  4  9 16]
Square root of b: [3.16227766 4.47213595 5.47722558 6.32455532]



## 3. Indexing and Slicing

In [5]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print(f"Original array:\n{arr}\n")
print(f"Element at [1, 2]: {arr[1, 2]}")
print(f"First row: {arr[0, :]}")
print(f"Second column: {arr[:, 1]}")
print(f"Subarray:\n{arr[0:2, 1:3]}\n")

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Element at [1, 2]: 7
First row: [1 2 3 4]
Second column: [ 2  6 10]
Subarray:
[[2 3]
 [6 7]]



In [6]:
# Boolean indexing
print(f"Elements > 5:\n{arr[arr > 5]}\n")

Elements > 5:
[ 6  7  8  9 10 11 12]



## 4. Statistical Operations

In [7]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(f"Data: {data}")
print(f"Mean: {np.mean(data)}")
print(f"Median: {np.median(data)}")
print(f"Standard Deviation: {np.std(data)}")
print(f"Variance: {np.var(data)}")
print(f"Min: {np.min(data)}")
print(f"Max: {np.max(data)}")
print(f"Sum: {np.sum(data)}\n")

Data: [ 1  2  3  4  5  6  7  8  9 10]
Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25
Min: 1
Max: 10
Sum: 55



## 5. Matrix Operations (Important for ML!)

In [8]:
# Matrix multiplication
X = np.array([[1, 2], [3, 4]])
Y = np.array([[5, 6], [7, 8]])

print(f"Matrix X:\n{X}\n")
print(f"Matrix Y:\n{Y}\n")
print(f"Matrix multiplication (X @ Y):\n{X @ Y}\n")
print(f"Transpose of X:\n{X.T}\n")

Matrix X:
[[1 2]
 [3 4]]

Matrix Y:
[[5 6]
 [7 8]]

Matrix multiplication (X @ Y):
[[19 22]
 [43 50]]

Transpose of X:
[[1 3]
 [2 4]]



In [9]:
# Dot product (very common in ML)
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
print(f"Dot product of {v1} and {v2}: {np.dot(v1, v2)}\n")

Dot product of [1 2 3] and [4 5 6]: 32



## 6. Broadcasting (Key ML Concept)

In [10]:
# Broadcasting allows operations on arrays of different shapes
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
vector = np.array([10, 20, 30])

print(f"Matrix:\n{matrix}\n")
print(f"Vector: {vector}\n")
print(f"Matrix + Vector (broadcasting):\n{matrix + vector}\n")

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Vector: [10 20 30]

Matrix + Vector (broadcasting):
[[11 22 33]
 [14 25 36]
 [17 28 39]]



## Exercise: Try These!

1. Create a 5x5 matrix of random numbers between 0 and 100
2. Find all elements greater than 50
3. Calculate the mean of each column
4. Normalize the matrix (subtract mean, divide by std dev)

In [11]:
# Your code here
