# Table of Contents

1. [Introduction](#introduction)
2. [Why NumPy Arrays?](#why-numpy-arrays)
3. [Creating Arrays](#creating-arrays)
4. [Array Properties](#array-properties)
5. [Array vs List Comparison](#array-vs-list-comparison)
6. [Reshaping Arrays](#reshaping-arrays)
7. [Common Errors](#common-errors)
8. [Summary Quiz](#summary-quiz)


# NumPy Basics

NumPy is a powerful Python library for numerical computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on them efficiently.

## What is a NumPy Array?
A NumPy array ("ndarray") is a grid of values, all of the same type, indexed by a tuple of nonnegative integers.

### Creating a NumPy Array
**Syntax:**
```python
import numpy as np
arr = np.array([1, 2, 3])
```

### Array Properties
- `shape`: Dimensions of the array
- `dtype`: Data type of the array elements
- `size`: Total number of elements
- `ndim`: Number of dimensions
- `itemsize`: Size in bytes of each element

---

## Why NumPy Arrays?

- NumPy arrays are faster and use less memory than Python lists.
- They support vectorized operations (apply operations to all elements at once).
- Useful for mathematical and scientific computing.

**Example:**
- Adding two lists vs. two arrays.


In [ ]:
# Python list vs NumPy array
py_list1 = [1, 2, 3]
py_list2 = [4, 5, 6]
print('List addition:', py_list1 + py_list2)  # Concatenates lists

import numpy as np
np_arr1 = np.array([1, 2, 3])
np_arr2 = np.array([4, 5, 6])
print('Array addition:', np_arr1 + np_arr2)  # Element-wise addition

In [4]:
import numpy as np

In [5]:
# Create a 1D array from a Python list
arr = np.array([1, 2, 3, 4, 5])
print('1D array:', arr)

1D array: [1 2 3 4 5]


In [6]:
# Create a 2D array (matrix)
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print('2D array:\n', arr2d)

2D array:
 [[1 2 3]
 [4 5 6]]


In [7]:
# Array properties for 1D array
print('Array Shape:', arr.shape)
print('Array Data Type:', arr.dtype)
print('Array Size:', arr.size)
print('Array Dimensions:', arr.ndim)
print('Array Item Size (bytes):', arr.itemsize)

Array Shape: (5,)
Array Data Type: int64
Array Size: 5
Array Dimensions: 1
Array Item Size (bytes): 8


In [8]:
# Array properties for 2D array
print('2D Array Shape:', arr2d.shape)
print('2D Array Data Type:', arr2d.dtype)
print('2D Array Size:', arr2d.size)
print('2D Array Dimensions:', arr2d.ndim)
print('2D Array Item Size (bytes):', arr2d.itemsize)

2D Array Shape: (2, 3)
2D Array Data Type: int64
2D Array Size: 6
2D Array Dimensions: 2
2D Array Item Size (bytes): 8


## Reshaping Arrays

You can change the shape of an array using the `reshape` method.

**Example:**

In [ ]:
# Reshape a 1D array to 2D
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)
print('Original:', arr)
print('Reshaped (2x3):\n', reshaped)

## More Examples

### Example: Creating arrays with different data types
```python
arr_int = np.array([1, 2, 3], dtype=np.int32)
arr_float = np.array([1, 2, 3], dtype=np.float64)
print(arr_int, arr_int.dtype)
print(arr_float, arr_float.dtype)
```

### Example: Checking array properties
```python
arr = np.array([[1, 2, 3], [4, 5, 6]])
print('Shape:', arr.shape)
print('Size:', arr.size)
print('Number of dimensions:', arr.ndim)
```

In [9]:
# Checking array properties
arr = np.array([[1, 2, 3], [4, 5, 6]])
print('Shape:', arr.shape)
print('Size:', arr.size)
print('Number of dimensions:', arr.ndim)

Shape: (2, 3)
Size: 6
Number of dimensions: 2


In [10]:
# Creating arrays with different data types
arr_int = np.array([1, 2, 3], dtype=np.int32)
arr_float = np.array([1, 2, 3], dtype=np.float64)
print(arr_int, arr_int.dtype)
print(arr_float, arr_float.dtype)

[1 2 3] int32
[1. 2. 3.] float64


## Common Errors

- **Shape mismatch:** Trying to reshape to an incompatible shape or operate on arrays of different shapes.
- **Type errors:** Mixing lists and arrays in operations.

**Example:**
```python
arr = np.array([1, 2, 3])
# arr.reshape(2, 2)  # ValueError: cannot reshape array of size 3 into shape (2,2)
```


## Summary Quiz

1. What is the main advantage of NumPy arrays over Python lists?
2. How do you check the shape of a NumPy array?
3. What happens if you try to add two lists in Python? What about two arrays?
4. How do you reshape a 1D array of length 6 into a 2D array with 2 rows?

*Try to answer these before moving on!*