# Table of Contents

1. [Introduction](#introduction)
2. [Why Array Creation?](#why-array-creation)
3. [Array Creation Functions](#array-creation-functions)
4. [Examples](#examples)
5. [Common Errors](#common-errors)
6. [Summary Quiz](#summary-quiz)


# Array Creation

NumPy provides many ways to create arrays for different purposes.

## Common Array Creation Functions
- `np.array()`: Create an array from a Python list or tuple
- `np.arange()`: Create arrays with regularly incrementing values
- `np.linspace()`: Create arrays with a specified number of values between a start and stop value
- `np.zeros()`, `np.ones()`: Create arrays filled with zeros or ones
- `np.eye()`: Create an identity matrix
- `np.diag()`: Create a diagonal matrix
- `np.vander()`: Create a Vandermonde matrix

---

## Why Array Creation?

- Creating arrays efficiently is essential for scientific computing and data analysis.
- NumPy provides many functions to create arrays for different needs: sequences, filled arrays, identity matrices, and more.
- Understanding these functions helps you write faster and more readable code.


In [5]:
import numpy as np

In [6]:
# np.arange: Create a 1D array with values from 0 to 10 (step 2)
arr = np.arange(0, 11, 2)
print('arange:', arr)

arange: [ 0  2  4  6  8 10]


In [7]:
# np.linspace: Create 10 values between 0 and 5 (inclusive)
arr = np.linspace(0, 5, 10)
print('linspace:', arr)

linspace: [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [8]:
# np.zeros: Create an array filled with zeros
zeros_arr = np.zeros((2, 3))
print('zeros:', zeros_arr)

zeros: [[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
# np.ones: Create an array filled with ones
ones_arr = np.ones((2, 3))
print('ones:', ones_arr)

ones: [[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
# np.eye: Identity matrix
eye_arr = np.eye(3)
print('eye:', eye_arr)

eye: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
# np.diag: Diagonal matrix
diag_arr = np.diag([1, 2, 3, 4])
print('diag:', diag_arr)

diag: [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [12]:
# np.vander: Vandermonde matrix
vander_arr = np.vander([1, 2, 3, 4], 3)
print('vander:', vander_arr)

vander: [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]]


## Common Errors

- **Shape mismatch:** Passing wrong shape arguments to creation functions.
- **Type errors:** Using unsupported data types.
- **Confusing `arange` and `linspace`:** `arange` uses step, `linspace` uses number of elements.

**Example:**
```python
# np.zeros(2, 3)  # TypeError: shape must be a tuple
np.zeros((2, 3))  # Correct
```


## More Examples

### Example: Creating arrays with a specific data type
```python
arr = np.arange(5, 10, dtype=np.float64)
print(arr, arr.dtype)
```

### Example: 2D identity matrix of size 2x3
```python
arr = np.eye(2, 3)
print(arr)
```

## Summary Quiz

1. What is the difference between `np.arange` and `np.linspace`?
2. How do you create a 3x3 array of ones?
3. What does `np.eye(4)` return?
4. How do you create a diagonal matrix with values [1, 2, 3]?

*Try to answer these before moving on!*