# Table of Contents

1. [Introduction](#introduction)
2. [Why Random Numbers?](#why-random-numbers)
3. [Random Number Functions](#random-number-functions)
4. [Examples](#examples)
5. [Common Errors](#common-errors)
6. [Summary Quiz](#summary-quiz)


# Random Numbers in NumPy

NumPy provides several functions to generate random numbers and arrays. These are useful for simulations, testing, and initializing data.

## Common Random Functions
- `np.random.rand()`: Uniform distribution over [0, 1)
- `np.random.randint()`: Random integers from a range
- `np.random.randn()`: Standard normal distribution (mean 0, std 1)
- `np.random.uniform()`: Uniform distribution over a custom interval

---

## Why Random Numbers?

- Random numbers are essential for simulations, testing, sampling, and initializing machine learning models.
- NumPy provides fast and flexible random number generation for arrays of any shape.


## About `np.random.rand`


- **Purpose:** Generates random numbers from a uniform distribution over [0, 1).
- **Shape:** Pass one or more integers as arguments to specify the shape of the output array. For example, `np.random.rand(2, 3)` creates a 2x3 array.
- **Data type:** The output is always of float type.
- **Reproducibility:** You can set a random seed using `np.random.seed()` to get repeatable results.
- **Usage:** Useful for simulations, initializing weights in machine learning, and random sampling.

**Example:**
```python
np.random.seed(42)  # Set the seed for reproducibility
arr = np.random.rand(2, 3)
print(arr)
```

In [2]:
import numpy as np

In [3]:
# np.random.rand: Uniform random numbers between 0 and 1
arr = np.random.rand(3, 4)
print('rand:', arr)

rand: [[0.53685601 0.3141766  0.10292257 0.79573985]
 [0.49879479 0.90173861 0.81705657 0.62736854]
 [0.16201572 0.61900593 0.05577968 0.05239636]]


In [4]:
# np.random.randint: Random integers between 1 and 9 (inclusive of 1, exclusive of 10)
arr = np.random.randint(1, 10, (3, 4))
print('randint:', arr)

randint: [[1 1 7 3]
 [2 8 7 9]
 [6 6 2 5]]


In [5]:
# np.random.randn: Standard normal distribution
arr = np.random.randn(3, 4)
print('randn:', arr)

randn: [[-1.63521742e+00  8.10023728e-02 -2.96499804e-01  2.59929870e-01]
 [ 1.35316172e+00  1.54224556e+00 -2.73162603e+00  2.74658414e-01]
 [ 1.35491798e+00 -8.09948544e-01  1.04565423e-03  6.67774569e-03]]


In [6]:
# np.random.uniform: Uniform random numbers between 0 and 42
arr = np.random.uniform(0, 42, size=(3, 4))
print('uniform:', arr)

uniform: [[31.6545099  33.53102285 25.22216633 24.36187818]
 [14.66755847 34.27519918 22.62515824 29.52423932]
 [25.72441388 27.82209433  3.13497096 12.88416105]]


## Common Errors

- **Shape mismatch:** Passing wrong shape arguments to random functions.
- **Type errors:** Using unsupported data types or wrong argument order.
- **Forgetting to set a seed:** Results are not reproducible unless you use `np.random.seed()`.

**Example:**
```python
# np.random.randint(5, size=2, 3)  # TypeError: size must be a tuple or int
np.random.randint(5, size=(2, 3))  # Correct
```


## More Examples

### Example: 1D random integer array
```python
arr = np.random.randint(0, 5, 8)
print(arr)
```

### Example: Setting a random seed for reproducibility
```python
np.random.seed(42)
print(np.random.rand(2, 2))
```

## Summary Quiz

1. What does `np.random.rand(2, 3)` return?
2. How do you generate random integers between 0 and 9 in a 4x4 array?
3. What is the difference between `rand` and `randn`?
4. How do you make random results reproducible?

*Try to answer these before moving on!*