# Table of Contents

1. [Introduction](#introduction)
2. [Why Indexing & Slicing?](#why-indexing--slicing)
3. [Types of Indexing](#types-of-indexing)
4. [Examples](#examples)
5. [Common Errors](#common-errors)
6. [Summary Quiz](#summary-quiz)


# Indexing & Slicing

Indexing and slicing are ways to access and modify parts of a NumPy array.

## Types of Indexing
- **Basic Indexing:** Accessing elements by their position
- **Slicing:** Extracting subarrays using the `:` operator
- **Advanced Indexing:** Using lists/arrays of indices
- **Boolean Indexing:** Using boolean conditions to filter elements

---

## Why Indexing & Slicing?

- Indexing and slicing let you access, modify, and analyze specific parts of your data efficiently.
- They are essential for data cleaning, feature selection, and subsetting arrays for analysis.


In [2]:
import numpy as np

In [3]:
# View vs Copy
arr = np.array([1, 2, 3, 4, 5])
arr_view = arr[1:4]  # This is a view, not a copy
print('Original array:', arr)
arr_view[0] = 99
print('After modifying view:')
print('Original array:', arr)
print('View array:', arr_view)

Original array: [1 2 3 4 5]
After modifying view:
Original array: [ 1 99  3  4  5]
View array: [99  3  4]


In [4]:
# Copy example
arr = np.array([1, 2, 3, 4, 5])
arr_copy = arr.copy()  # This is a true copy
arr_copy[1] = 20
print('After modifying copy:')
print('Original array:', arr)
print('Copy array:', arr_copy)

After modifying copy:
Original array: [1 2 3 4 5]
Copy array: [ 1 20  3  4  5]


## Slicing Syntax

```python
arr[start:stop:step]
# start: index to start (inclusive)
# stop: index to stop (exclusive)
# step: step size (optional)
```

### Example: 2D Slicing
```python
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])
print(arr[0:2, 1:3])  # rows 0-1, columns 1-2
```

In [5]:
# Advanced Indexing
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
row_indices = [0, 2]
col_indices = [1, 3]
adv_indexed = arr[row_indices, :][:, col_indices]
print('Advanced indexed array (rows 0 & 2, cols 1 & 3):\n', adv_indexed)

Advanced indexed array (rows 0 & 2, cols 1 & 3):
 [[ 2  4]
 [10 12]]


## Boolean Indexing Example

```python
arr = np.array([10, 25, 30, 45, 50, 65, 70])
filtered_arr = arr[arr > 30]
print(filtered_arr)
```

In [6]:
# 2D slicing
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])
print("Original array:\n", arr)
row_slice = arr[0:2]  # first two rows
print("Sliced rows (0 to 1):\n", row_slice)
col_slice = arr[:, 1:3]  # all rows, columns 1 to 2
print("Sliced columns (1 to 2):\n", col_slice)
sub_array = arr[0:2, 1:3]  # rows 0 to 1, columns 1 to 2
print("Sliced subarray (rows 0-1, cols 1-2):\n", sub_array)

Original array:
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
Sliced rows (0 to 1):
 [[10 20 30 40]
 [50 60 70 80]]
Sliced columns (1 to 2):
 [[ 20  30]
 [ 60  70]
 [100 110]]
Sliced subarray (rows 0-1, cols 1-2):
 [[20 30]
 [60 70]]


In [7]:
# Advanced indexing example
row_indices = [0, 2]
col_indices = [1, 3]
adv_indexed = arr[row_indices, :][:, col_indices]
print("Advanced indexed array (rows 0 & 2, cols 1 & 3):\n", adv_indexed)

Advanced indexed array (rows 0 & 2, cols 1 & 3):
 [[ 20  40]
 [100 120]]


In [8]:
# Slicing with step and negative step
arr = np.array([[10, 20, 30, 40, 50],
                [60, 70, 80, 90, 100],
                [110, 120, 130, 140, 150]])
sliced_step = arr[::2, ::2]  # every second row and every second column
print("Original array:\n", arr)
print("Sliced array with step 2:\n", sliced_step)

arr1 = np.array([10, 20, 30, 40, 50, 60])
reversed_arr = arr1[::-1]  # reverse the array
print("Original array:", arr1)
print("Reversed array:", reversed_arr)

Original array:
 [[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]]
Sliced array with step 2:
 [[ 10  30  50]
 [110 130 150]]
Original array: [10 20 30 40 50 60]
Reversed array: [60 50 40 30 20 10]


## Common Errors

- **Shape mismatch:** Trying to index or slice with incompatible shapes.
- **Type errors:** Using lists instead of arrays for advanced indexing.
- **Confusing view vs copy:** Modifying a view changes the original array, but modifying a copy does not.

**Example:**
```python
arr = np.array([1, 2, 3, 4])
view = arr[1:3]
view[0] = 99  # arr is also changed!
```


## Summary Quiz

1. What is the difference between a view and a copy in NumPy?
2. How do you select the first two rows and last two columns of a 2D array?
3. What does boolean indexing allow you to do?
4. How do you reverse a 1D array?

*Try to answer these before moving on!*