In [2]:
import numpy as np

In [3]:
#list into array

arr = np.array([1, 2, 3, 4, 5])
print(arr)

arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d)

print("Array Shape:", arr.shape)
print("2D Array Shape:", arr2d.shape)

print("Array Data Type:", arr.dtype)
print("2D Array Data Type:", arr2d.dtype)

print("Array Size:", arr.size)
print("2D Array Size:", arr2d.size)

print("Array Dimensions:", arr.ndim)
print("2D Array Dimensions:", arr2d.ndim)

print("Array Item Size (bytes):", arr.itemsize)
print("2D Array Item Size (bytes):", arr2d.itemsize)



[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
Array Shape: (5,)
2D Array Shape: (2, 3)
Array Data Type: int64
2D Array Data Type: int64
Array Size: 5
2D Array Size: 6
Array Dimensions: 1
2D Array Dimensions: 2
Array Item Size (bytes): 8
2D Array Item Size (bytes): 8


In [4]:
#aggregation functions
print("Array:", arr)
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Max:", np.max(arr))
print("Min:", np.min(arr))
print("Standard Deviation:", np.std(arr))
print("Variance:", np.var(arr))
print("Median:", np.median(arr))
print("Product:", np.prod(arr))
print("Cumulative Sum:", np.cumsum(arr))
print("Cumulative Product:", np.cumprod(arr))
print("Unique Elements:", np.unique(arr))

print("Array:", arr2d)
print("2D Array:\n", arr2d)
print("Sum:", np.sum(arr2d))
print("Mean:", np.mean(arr2d))
print("Max:", np.max(arr2d))
print("Min:", np.min(arr2d))
print("Standard Deviation:", np.std(arr2d))
print("Variance:", np.var(arr2d))
print("Median:", np.median(arr2d))
print("Product:", np.prod(arr2d))
print("Cumulative Sum:", np.cumsum(arr2d))
print("Cumulative Product:", np.cumprod(arr2d))
print("Unique Elements:", np.unique(arr2d))

Array: [1 2 3 4 5]
Sum: 15
Mean: 3.0
Max: 5
Min: 1
Standard Deviation: 1.4142135623730951
Variance: 2.0
Median: 3.0
Product: 120
Cumulative Sum: [ 1  3  6 10 15]
Cumulative Product: [  1   2   6  24 120]
Unique Elements: [1 2 3 4 5]
Array: [[1 2 3]
 [4 5 6]]
2D Array:
 [[1 2 3]
 [4 5 6]]
Sum: 21
Mean: 3.5
Max: 6
Min: 1
Standard Deviation: 1.707825127659933
Variance: 2.9166666666666665
Median: 3.5
Product: 720
Cumulative Sum: [ 1  3  6 10 15 21]
Cumulative Product: [  1   2   6  24 120 720]
Unique Elements: [1 2 3 4 5 6]


In [5]:
#limit data type
arr_dtype = np.array([1, 142, 3], dtype=np.int8)

OverflowError: Python integer 142 out of bounds for int8

In [ ]:
arr_dtype = np.array([1, 142, 3], dtype=np.int16)
print(arr_dtype)

'''
np.int8 = 8 bits = -128 to 127
np.int16 = 16 bits = -32,768 to 32,767
np.int32 = 32 bits = -2,147,483,648 to 2,147,483,647
np.int64 = 64 bits = -9,223,372,036,854,775,808 to 9,223,372,036,854,775,807
np.float16 = 16 bits = 1.0e-3 to 6.5e4
np.float32 = 32 bits = 1.2e-38 to 3.4e38
np.float64 = 64 bits = 2.3e-308 to 1.7e308
np.complex64 = 64 bits = 2x32-bit floats
np.complex128 = 128 bits = 2x64-bit floats
'''

[  1 142   3]


'\nnp.int8 = 8 bits = -128 to 127\nnp.int16 = 16 bits = -32,768 to 32,767\nnp.int32 = 32 bits = -2,147,483,648 to 2,147,483,647\nnp.int64 = 64 bits = -9,223,372,036,854,775,808 to 9,223,372,036,854,775,807\nnp.float16 = 16 bits = 1.0e-3 to 6.5e4\nnp.float32 = 32 bits = 1.2e-38 to 3.4e38\nnp.float64 = 64 bits = 2.3e-308 to 1.7e308\nnp.complex64 = 64 bits = 2x32-bit floats\nnp.complex128 = 128 bits = 2x64-bit floats\n'

In [ ]:
#intrinsic numpy array creation methods

# one dimensional array

arr = np.arange(0, 11, 2)  # start, stop, step
print(arr)

arr = np.arange(5,10, dtype=np.float64)  # start, stop, default step=1, dtype
print(arr)

arr = np.linspace(0, 5, 10)  # start, stop, number of elements
print(arr)

[ 0  2  4  6  8 10]
[5. 6. 7. 8. 9.]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [ ]:
# two dimensional array

arr = np.eye(3)  # identity matrix of size n x n
print(arr)

arr = np.eye(2, 3)  # identity matrix of size m x n
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]]


In [ ]:
#numpy.diag

arr = np.diag([1, 2, 3, 4]) # create a 2D array with given elements on the diagonal
print(arr)

arr = np.diag([1, 2, 3, 4], 1) # create a 2D array with given elements on the k-th diagonal
print(arr)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


In [ ]:
# numpy.vander (x,n) where x is list or tuple, n is number of columns

arr = np.vander([1, 2, 3, 4], 3)  # list, number of columns
print(arr)

arr=np.linspace(1,4,4)  # linspace
print(arr)

arr = np.vander(np.linspace(1, 4, 4), 4)  # linspace, number of columns
print(arr)

[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]]
[1. 2. 3. 4.]
[[ 1.  1.  1.  1.]
 [ 8.  4.  2.  1.]
 [27.  9.  3.  1.]
 [64. 16.  4.  1.]]


In [ ]:
# genera ndaarray with create function

arr = np.zeros((3,4))  # shape
print(arr)

arr= np.zeros((2,3,4))
print(arr)

arr = np.ones((3,4))  # shape
print(arr)

arr= np.ones((2,3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [ ]:
# random
arr = np.random.rand(3,4)  # shape
print(arr)

arr= np.random.rand(2,3,4)
print(arr)
# random always generates values between 0 and 1

arr = np.random.randint(1, 10, (3,4))  # low, high, shape
print(arr)

arr= np.random.randint(1, 100, (2,3,4))
print(arr)

[[0.32065311 0.66225619 0.06025906 0.03678511]
 [0.69831181 0.38784774 0.3528912  0.22636496]
 [0.41995958 0.27300743 0.44632213 0.28874749]]
[[[0.65154535 0.04435496 0.71799363 0.2345754 ]
  [0.58836756 0.76587748 0.18820872 0.84174793]
  [0.39556424 0.45029399 0.30610234 0.35841888]]

 [[0.31875335 0.76902138 0.9145631  0.7445913 ]
  [0.72816513 0.20748421 0.61790555 0.11617032]
  [0.57935982 0.82263461 0.52832798 0.11872337]]]
[[4 7 1 4]
 [7 5 5 1]
 [6 4 6 1]]
[[[35 97 40 89]
  [75 59 61 44]
  [21 70 76 98]]

 [[57 33 99 76]
  [92 48 87 26]
  [35 80  5 29]]]


In [ ]:

arr= np.random.randn(3,4)  # randn is for standard normal distribution
print(arr)

arr= np.random.randn(2,3,4)
print(arr)

arr= np.random.uniform(0, 42, size=(3,4))  # low, high, shape
print(arr)

[[ 0.49671415 -0.1382643   0.64768854  1.52302986]
 [-0.23415337 -0.23413696  1.57921282  0.76743473]
 [-0.46947439  0.54256004 -0.46341769 -0.46572975]]
[[[ 0.24196227 -1.91328024 -1.72491783 -0.56228753]
  [-1.01283112  0.31424733 -0.90802408 -1.4123037 ]
  [ 1.46564877 -0.2257763   0.0675282  -1.42474819]]

 [[-0.54438272  0.11092259 -1.15099358  0.37569802]
  [-0.60063869 -0.29169375 -0.60170661  1.85227818]
  [-0.01349722 -1.05771093  0.82254491 -1.22084365]]]
[[13.0918652  21.84285689 22.96183173  7.76388713]
 [40.72255437 32.55557858 39.45895555 37.58274872]
 [25.11179911 38.71871787  3.71668509  8.23128022]]


In [ ]:
# copying arrays 1. View vs Copy

arr = np.array([1, 2, 3, 4, 5])
arr_view = arr.view()
arr_copy = arr.copy()
print("Original array:", arr)
arr_view[0] = 10
print("After modifying view:")
print("Original array:", arr)
print("View array:", arr_view)
arr_copy[1] = 20
print("After modifying copy:")
print("Original array:", arr)
print("Copy array:", arr_copy)

arr2 = arr #this is same as view, not copy
arr2[2] = 30
print("After modifying arr2 (reference):")
print("Original array:", arr)
print("arr2 array:", arr2)

Original array: [1 2 3 4 5]
After modifying view:
Original array: [10  2  3  4  5]
View array: [10  2  3  4  5]
After modifying copy:
Original array: [10  2  3  4  5]
Copy array: [ 1 20  3  4  5]
After modifying arr2 (reference):
Original array: [10  2 30  4  5]
arr2 array: [10  2 30  4  5]


In [ ]:
#slicing and changing values does not create a copy, it creates a view

arr = np.array([10, 20, 30, 40, 50])
sliced_arr = arr[1:4]  # elements from index 1 to 3
print("Original array:", arr)
print("Sliced array:", sliced_arr)
sliced_arr[0] = 99
print("After modifying sliced array:")
print("Original array:", arr)
print("Sliced array:", sliced_arr)

Original array: [10 20 30 40 50]
Sliced array: [20 30 40]
After modifying sliced array:
Original array: [10 99 30 40 50]
Sliced array: [99 30 40]


In [ ]:
#slicing and indexing
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])   

print("Original array:\n", arr)
#slicing rows
row_slice = arr[0:2] # or arr[0:2, :]  # first two rows, all columns
print("Sliced rows (0 to 1):\n", row_slice)
#slicing columns
col_slice = arr[:, 1:3]  # all rows, columns 1 to 2
print("Sliced columns (1 to 2):\n", col_slice)      
#slicing subarray
sub_array = arr[0:2, 1:3]  # rows 0 to 1, columns 1 to 2
print("Sliced subarray (rows 0-1, cols 1-2):\n", sub_array)
#advanced indexing  
row_indices = [0, 2]
col_indices = [1, 3]
adv_indexed = arr[row_indices, :][:, col_indices]  # select specific rows and columns
print("Advanced indexed array (rows 0 & 2, cols 1 & 3):\n", adv_indexed)

Original array:
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
Sliced rows (0 to 1):
 [[10 20 30 40]
 [50 60 70 80]]
Sliced columns (1 to 2):
 [[ 20  30]
 [ 60  70]
 [100 110]]
Sliced subarray (rows 0-1, cols 1-2):
 [[20 30]
 [60 70]]
Advanced indexed array (rows 0 & 2, cols 1 & 3):
 [[ 20  40]
 [100 120]]


In [ ]:
#slicing with step in 2d
arr = np.array([[10, 20, 30, 40, 50],
                [60, 70, 80, 90, 100],
                [110, 120, 130, 140, 150],
                [160, 170, 180, 190, 200],
                [210, 220, 230, 240, 250]])

sliced_step = arr[::2, ::2]  # every second row and every second column
print("Original array:\n", arr)
print("Sliced array with step 2:\n", sliced_step)   

Original array:
 [[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]
 [210 220 230 240 250]]
Sliced array with step 2:
 [[ 10  30  50]
 [110 130 150]
 [210 230 250]]


In [ ]:
#advance slicing

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

row_indices = [0, 2]
col_indices = [1, 3]

# Step 1: arr[row_indices, :] → Select rows 0 and 2
# [[1, 2, 3, 4],
#  [9, 10, 11, 12]]

# Step 2: [:, col_indices] → Select columns 1 and 3
adv_indexed = arr[row_indices, :][:, col_indices]
# [[2, 4],
#  [10, 12]]
print("Advanced indexed array (rows 0 & 2, cols 1 & 3):\n", adv_indexed)

Advanced indexed array (rows 0 & 2, cols 1 & 3):
 [[ 2  4]
 [10 12]]


In [ ]:
#slicing with negative step
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
reversed_arr = arr[::-1]  # reverse the array
print("Original array:", arr)
print("Reversed array:", reversed_arr)  

Original array: [ 10  20  30  40  50  60  70  80  90 100]
Reversed array: [100  90  80  70  60  50  40  30  20  10]


In [ ]:
#slicing with negative step in 2d
arr = np.array([[10, 20, 30, 40, 50],
                [60, 70, 80, 90, 100],
                [110, 120, 130, 140, 150],
                [160, 170, 180, 190, 200],
                [210, 220, 230, 240, 250]])
reversed_2d = arr[::-1, ::-1]  # reverse both rows and columns
print("Original array:\n", arr)
print("Reversed 2D array:\n", reversed_2d)

arr_sub = arr[1:4:-1, 1:4:-1]  # reverse rows and columns in a subarray
print("Subarray with negative step:\n", arr_sub)
#Note: result will be empty because slicing with negative step requires start index to be greater than stop index

arr_sub = arr[4:1:-1, 4:1:-1]  # reverse rows and columns in a subarray
print("Subarray with negative step:\n", arr_sub)

Original array:
 [[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]
 [210 220 230 240 250]]
Reversed 2D array:
 [[250 240 230 220 210]
 [200 190 180 170 160]
 [150 140 130 120 110]
 [100  90  80  70  60]
 [ 50  40  30  20  10]]
Subarray with negative step:
 []
Subarray with negative step:
 [[250 240 230]
 [200 190 180]
 [150 140 130]]


In [ ]:
# Arithmetic operations on arrays
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])
print("Array 1:", arr1)
print("Array 2:", arr2)
print("Addition:", arr1 + arr2) # element-wise addition: 10+1, 20+2, 30+3, 40+4
print("Subtraction:", arr1 - arr2) # element-wise subtraction: 10-1, 20-2, 30-3, 40-4
print("Multiplication:", arr1 * arr2) # element-wise multiplication: 10*1, 20*2, 30*3, 40*4
print("Division:", arr1 / arr2) # element-wise division: 10/1, 20/2, 30/3, 40/4
print("Addition with scalar:", arr1 + 5) # add 5 to each element: 10+5, 20+5, 30+5, 40+5
print("Subtraction with scalar:", arr1 - 5) # subtract 5 from each element: 10-5, 20-5, 30-5, 40-5
print("Multiplication with scalar:", arr1 * 5) # multiply each element by 5: 10*5, 20*5, 30*5, 40*5
print("Division with scalar:", arr1 / 5) # divide each element by 5: 10/5, 20/5, 30/5, 40/5


Array 1: [10 20 30 40]
Array 2: [1 2 3 4]
Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]
Addition with scalar: [15 25 35 45]
Subtraction with scalar: [ 5 15 25 35]
Multiplication with scalar: [ 50 100 150 200]
Division with scalar: [2. 4. 6. 8.]


In [9]:
# vectorized operations
arr = np.array([1,2,3,4,5])

print(np.sqrt(arr))        # square root
print(np.exp(arr))         # exponential    
print(np.log(arr))         # natural logarithm
print(np.sin(arr))         # sine
print(np.cos(arr))         # cosine
print(np.pi)

arr = np.array([0.5, 1.2, 1.5, 2.5, 3.7])
print(np.ceil(arr))       # ceiling
print(np.floor(arr))      # floor
print(np.round(arr))      # round to nearest integer

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
3.141592653589793
[1. 2. 2. 3. 4.]
[0. 1. 1. 2. 3.]
[0. 1. 2. 2. 4.]


In [10]:
# elements wise operations between two arrays
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

print("Addition:", arr1 + arr2) # element-wise addition
print("Subtraction:", arr1 - arr2) # element-wise subtraction
print("Multiplication:", arr1 * arr2) # element-wise multiplication
print("Division:", arr1 / arr2) # element-wise division
print("Power:", arr1 ** arr2) # element-wise exponentiation

Addition: [ 6  8 10 12]
Subtraction: [-4 -4 -4 -4]
Multiplication: [ 5 12 21 32]
Division: [0.2        0.33333333 0.42857143 0.5       ]
Power: [    1    64  2187 65536]


In [14]:
# comparison operations
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([15, 20, 25, 35])
print("Equal:", arr1 == arr2)           # element-wise equality
print("Not Equal:", arr1 != arr2)       # element-wise inequality
print("Greater Than:", arr1 > arr2)     # element-wise greater than
print("Less Than:", arr1 < arr2)        # element-wise less than
print("Greater Than or Equal:", arr1 >= arr2) # element-wise greater than or equal
print("Less Than or Equal:", arr1 <= arr2)    # element-wise less than or equal
print(arr1 == 100)  # compare with scalar
print(arr1 < 25)    # compare with scalar
arr1[arr1<25] = 0  # filter elements less than 25 and set them to 0
print(arr1)

Equal: [False  True False False]
Not Equal: [ True False  True  True]
Greater Than: [False False  True  True]
Less Than: [ True False False False]
Greater Than or Equal: [False  True  True  True]
Less Than or Equal: [ True  True False False]
[False False False False]
[ True  True False False]
[ 0  0 30 40]


In [ ]:
# broadcasting

'''
Broadcasting allows NumPy to perform operations on arrays of different shapes in a way that makes sense mathematically. 
When operating on two arrays, NumPy compares their shapes element-wise from the trailing dimensions (rightmost) and 
applies the following rules:
1. If the arrays have a different number of dimensions, the shape of the smaller-dimensional array is 
    padded with ones on the left side until both shapes have the same length.
2. The sizes of the dimensions are compared element-wise. Two dimensions are compatible when:
    - They are equal, or
    - One of them is 1 
'''

In [ ]:
arr=np.array([[1,2,3],[3,4,5]])
print(arr.shape) # rows=2, columns=3
print(arr.size)  # total number of elements

(2, 3)
6


In [23]:
#broadcasting example 1: adding a scalar to an array
arr = np.array([[1, 2, 3],[4, 5, 6]])
scalar = 10
result = arr + scalar
print("Original array:")
print(arr)
print("Scalar value:", scalar)
print("Result after adding scalar:")
print(result)

Original array:
[[1 2 3]
 [4 5 6]]
Scalar value: 10
Result after adding scalar:
[[11 12 13]
 [14 15 16]]


In [ ]:
# broadcasting example 2: adding two arrays of different shapes - which follows broadcasting rules
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[10], [20], [30]])
result = arr1 + arr2
print(arr1.shape)  # (1, 3)
print(arr2.shape)  # (3, 1)
print("Array 1:")
print(arr1)
print("Array 2:")
print(arr2)
print("Result after broadcasting addition:")
print(result)

(1, 3)
(3, 1)
Array 1:
[[1 2 3]]
Array 2:
[[10]
 [20]
 [30]]
Result after broadcasting addition:
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [25]:
# broadcasting example 2: adding two arrays of different shapes - which does not follows broadcasting rules
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[10, 20]])  # Different number of columns
try:
    result = arr1 + arr2
except ValueError as e:
    print("Error:", e)

Error: operands could not be broadcast together with shapes (1,3) (1,2) 


In [27]:
#filtering the elements based on condition
arr = np.array([10, 25, 30, 45, 50, 65, 70])
filtered_arr = arr[arr > 30]  # filter elements greater than 30 
print("Original array:", arr)
print("Filtered array (elements > 30):", filtered_arr)
even = arr[arr % 2 == 0]  # filter even elements
print("Even elements:", even)
print("Odd elements:", arr[arr % 2 != 0])  # filter odd elements


Original array: [10 25 30 45 50 65 70]
Filtered array (elements > 30): [45 50 65 70]
Even elements: [10 30 50 70]
Odd elements: [25 45 65]


In [31]:
# using where function
arr = np.array([10, 25, 30, 45, 50, 65, 70])
indices = np.where(arr > 30)  # get indices of elements greater than 30
print("Original array:", arr)
print("Indices of elements greater than 30:", indices)
print("Elements greater than 30:", arr[indices])

#2d
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
indices = np.where(arr > 50)  # get indices of elements greater than 50
print("Original 2D array:\n", arr)
print("Indices of elements greater than 50:", indices)
print("Elements greater than 50:", arr[indices])

unchanged_shape = np.where(arr > 50, arr, -1)  # replace elements <= 50 with -1
print("Array with elements <= 50 replaced by -1:\n", unchanged_shape)   

Original array: [10 25 30 45 50 65 70]
Indices of elements greater than 30: (array([3, 4, 5, 6]),)
Elements greater than 30: [45 50 65 70]
Original 2D array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Indices of elements greater than 50: (array([1, 2, 2, 2]), array([2, 0, 1, 2]))
Elements greater than 50: [60 70 80 90]
Array with elements <= 50 replaced by -1:
 [[-1 -1 -1]
 [-1 -1 60]
 [70 80 90]]


In [32]:
# transpose of array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
transposed = arr.T
print("Original array:\n", arr)
print("Transposed array:\n", transposed)

Original array:
 [[1 2 3]
 [4 5 6]]
Transposed array:
 [[1 4]
 [2 5]
 [3 6]]


In [ ]:
# 3d array transpose (swapping axes) - numpy consider axes as 0,1,2
arr = np.array([[[1, 2],    
                 [3, 4]],
                
                [[5, 6],
                 [7, 8]]]) 

transposed_3d = arr.transpose(1, 0, 2)  # swap first and second axes
print("Original 3D array:\n", arr)
print("Transposed 3D array (swapping first and second axes):\n", transposed_3d)

Original 3D array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Transposed 3D array (swapping first and second axes):
 [[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [35]:
# matrix multiplication
A = np.array([[1, 2, 3],
              [4, 5, 6]])   
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])
C = np.dot(A, B)  # or C = A @ B
print("Matrix A:\n", A)
print("Matrix B:\n", B) 

print("Matrix C (A multiplied by B):\n", C) 

d= np.matmul(A,B)
print("Matrix C using matmul (A multiplied by B):\n", d)

Matrix A:
 [[1 2 3]
 [4 5 6]]
Matrix B:
 [[ 7  8]
 [ 9 10]
 [11 12]]
Matrix C (A multiplied by B):
 [[ 58  64]
 [139 154]]
Matrix C using matmul (A multiplied by B):
 [[ 58  64]
 [139 154]]


In [36]:
# matrix inversion
matrix = np.array([[4, 7],
                   [2, 6]]) 
inverse_matrix = np.linalg.inv(matrix)
print("Original matrix:\n", matrix)
print("Inverse matrix:\n", inverse_matrix)

Original matrix:
 [[4 7]
 [2 6]]
Inverse matrix:
 [[ 0.6 -0.7]
 [-0.2  0.4]]


In [37]:
# reshaping arrays
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])  
reshaped = arr.reshape(4, 2)  # reshape to 4 rows and 2 columns
print("Original array:\n", arr)
print("Reshaped array (4x2):\n", reshaped)

arr2 = np.array([1, 2, 3, 4, 5, 6])
reshaped2 = arr2.reshape(2, 3)  # reshape to 2
print("Original 1D array:\n", arr2)
print("Reshaped array (2x3):\n", reshaped2)

Original array:
 [[1 2 3 4]
 [5 6 7 8]]
Reshaped array (4x2):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Original 1D array:
 [1 2 3 4 5 6]
Reshaped array (2x3):
 [[1 2 3]
 [4 5 6]]


In [39]:
# ravel and flatten
arr = np.array([[1, 2, 3],  
                [4, 5, 6]])
raveled = arr.ravel()  # returns a flattened array (view)
flattened = arr.flatten()  # returns a flattened array (copy)   
print("Original array:\n", arr)
print("Raveled array (view):", raveled) 
print("Flattened array (copy):", flattened)
raveled[0] = 99
print("After modifying raveled array:")
print("Original array:\n", arr)
print("Raveled array (view):", raveled) 
flattened[1] = 88
print("After modifying flattened array:")   
print("Original array:\n", arr)
print("Flattened array (copy):", flattened)

Original array:
 [[1 2 3]
 [4 5 6]]
Raveled array (view): [1 2 3 4 5 6]
Flattened array (copy): [1 2 3 4 5 6]
After modifying raveled array:
Original array:
 [[99  2  3]
 [ 4  5  6]]
Raveled array (view): [99  2  3  4  5  6]
After modifying flattened array:
Original array:
 [[99  2  3]
 [ 4  5  6]]
Flattened array (copy): [ 1 88  3  4  5  6]


In [40]:
#splitting arrays
arr = np.array([[1, 2, 3, 4, 5, 6],
                [7, 8, 9, 10, 11, 12]])
split_arr = np.array_split(arr, 3, axis=1)  # split into 3 sub-arrays along columns
print("Original array:\n", arr) 
print("Split arrays along columns:")
for sub_arr in split_arr:  
    print(sub_arr) 
split_arr2 = np.array_split(arr, 2, axis=0)  # split into 2 sub-arrays along rows
print("Split arrays along rows:")   
for sub_arr in split_arr2:
    print(sub_arr)
    

Original array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Split arrays along columns:
[[1 2]
 [7 8]]
[[ 3  4]
 [ 9 10]]
[[ 5  6]
 [11 12]]
Split arrays along rows:
[[1 2 3 4 5 6]]
[[ 7  8  9 10 11 12]]


In [ ]:
#hsplit and vsplit
arr = np.array([[1, 2, 3, 4, 5, 6],
                [7, 8, 9, 10, 11, 12]]) 
hsplit_arr = np.hsplit(arr, 3)  # horizontal split into 3 sub-arrays
print("Original array:\n", arr)
print("Horizontally split arrays:")
for sub_arr in hsplit_arr:  
    print(sub_arr)          
vsplit_arr = np.vsplit(arr, 2)  # vertical split into 2 sub-arrays
print("Vertically split arrays:")
for sub_arr in vsplit_arr:
    print(sub_arr)


Original array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Horizontally split arrays:
[[1 2]
 [7 8]]
[[ 3  4]
 [ 9 10]]
[[ 5  6]
 [11 12]]
Vertically split arrays:
[[1 2 3 4 5 6]]
[[ 7  8  9 10 11 12]]


In [42]:
#hstack and vstack
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr2 = np.array([[7, 8, 9],
                 [10, 11, 12]])
hstacked = np.hstack((arr1, arr2))  # horizontal stacking
print("Array 1:\n", arr1)
print("Array 2:\n", arr2)
print("Horizontally stacked array:\n", hstacked)
vstacked = np.vstack((arr1, arr2))  # vertical stacking         
print("Vertically stacked array:\n", vstacked)

Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]
Horizontally stacked array:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
Vertically stacked array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [44]:
#concatenate
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr2 = np.array([[7, 8, 9],
                 [10, 11, 12]])

concatenated = np.concatenate((arr1, arr2), axis=0)  # concatenate along rows
print("Array 1:\n", arr1)
print("Array 2:\n", arr2)
print("Concatenated array along rows:\n", concatenated)

concatenated2 = np.concatenate((arr1, arr2), axis=1)  # concatenate along columns
print("Concatenated array along columns:\n", concatenated2)     


Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]
Concatenated array along rows:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Concatenated array along columns:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [45]:
#insert elements into array
arr = np.array([10, 20, 30, 40, 50])
new_arr = np.insert(arr, 2, 25)  # insert 25 at index 2
print("Original array:", arr)       
print("Array after insertion:", new_arr)

Original array: [10 20 30 40 50]
Array after insertion: [10 20 25 30 40 50]


In [46]:
# inserting into 2d array
arr2d = np.array([[1, 2, 3],    
                  [4, 5, 6]])
new_arr2d = np.insert(arr2d, 1, [10, 20, 30], axis=0)  # insert new row at index 1
print("Original 2D array:\n", arr2d)    
print("2D Array after insertion of new row at index 1:\n", new_arr2d)

Original 2D array:
 [[1 2 3]
 [4 5 6]]
2D Array after insertion of new row at index 1:
 [[ 1  2  3]
 [10 20 30]
 [ 4  5  6]]


In [47]:
#remove elements from array
arr = np.array([10, 20, 30, 40, 50])    
new_arr = np.delete(arr, 2)  # remove element at index 2
print("Original array:", arr)
print("Array after deletion:", new_arr)

#2d array
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
new_arr2d = np.delete(arr2d, 1, axis=0)  # remove row at index 1
print("Original 2D array:\n", arr2d)
print("2D Array after deletion of row at index 1:\n", new_arr2d)
new_arr2d_col = np.delete(arr2d, 2, axis=1)  # remove column at index 2
print("2D Array after deletion of column at index 2:\n", new_arr2d_col)

Original array: [10 20 30 40 50]
Array after deletion: [10 20 40 50]
Original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
2D Array after deletion of row at index 1:
 [[1 2 3]
 [7 8 9]]
2D Array after deletion of column at index 2:
 [[1 2]
 [4 5]
 [7 8]]
