In [2]:
import numpy as np

#### 1. Create a 1D array of numbers from 10 to 50, then extract all odd numbers from it.

In [3]:
arr = np.arange(11,50,2)
print(arr)

[11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49]


### 2. Create a 3x3 matrix with values ranging from 0 to 8. Replace all values greater than 4 with -1.

In [7]:
arr = np.random.randint(0,8, size=(3,3))
print(arr)
arr[arr > 4] = -1
print(arr)

[[2 0 1]
 [0 5 1]
 [2 1 7]]
[[ 2  0  1]
 [ 0 -1  1]
 [ 2  1 -1]]


### 3. Create two arrays: `a = [1, 2, 3, 4, 5]` and `b = [6, 7, 8, 9, 10]`. Stack them vertically and then horizontally.

In [8]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])

c=np.vstack((a,b))
print(c)

d=np.hstack((a,b))
print(d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10]


### 4. Create a 5x5 matrix with random values and find the minimum and maximum values.

In [10]:
a = np.random.rand(5,5)
print(a)

print(np.max(a))
print(np.min(a))

[[0.7140581  0.87539765 0.11975568 0.83778665 0.06777752]
 [0.1778182  0.38625366 0.61650493 0.38608417 0.34949456]
 [0.27164478 0.74355181 0.07943345 0.93399348 0.25384468]
 [0.9686873  0.10615429 0.7128754  0.92961949 0.04844788]
 [0.91410597 0.02104404 0.14985283 0.47285827 0.66313105]]
0.9686872974429317
0.02104403811141342


### 5. Create a 10x10 array with random values and normalize it (scale values between 0 and 1).

In [16]:
a = np.random.randint(1, 100, size=(10,10))

print(a)
#normalize the array
a_normalized = (a - np.min(a)) / (np.max(a) - np.min(a))
print(a_normalized)

[[76 99 23 85 35  2 16 34  5 41]
 [31 13 56 74 83 50 37 25 74 44]
 [30 28 54 34 21 29 63 69 56  5]
 [52 85 90 86 44 24 34 26 61 19]
 [67 42 10 89 58 15 88 81 80 69]
 [17 92 79 10 95  7 29 53 42 22]
 [36 68 59 23 72 61 45 51 69 29]
 [80 50  5 40 16 67 87 84 94 38]
 [ 4 93 34 16 91 94 18 54 90 71]
 [ 7 34 54 62 19 80 16 80 31 61]]
[[0.7628866  1.         0.21649485 0.8556701  0.34020619 0.
  0.1443299  0.32989691 0.03092784 0.40206186]
 [0.29896907 0.11340206 0.55670103 0.74226804 0.83505155 0.49484536
  0.36082474 0.2371134  0.74226804 0.43298969]
 [0.28865979 0.26804124 0.53608247 0.32989691 0.19587629 0.27835052
  0.62886598 0.69072165 0.55670103 0.03092784]
 [0.51546392 0.8556701  0.90721649 0.86597938 0.43298969 0.22680412
  0.32989691 0.24742268 0.60824742 0.17525773]
 [0.67010309 0.41237113 0.08247423 0.89690722 0.57731959 0.13402062
  0.88659794 0.81443299 0.80412371 0.69072165]
 [0.15463918 0.92783505 0.79381443 0.08247423 0.95876289 0.05154639
  0.27835052 0.5257732  0.41237113

### 6. Given an array `arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])`, reverse it without using any built-in reverse functions.

In [17]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr = arr[::-1]
print(arr)

[10  9  8  7  6  5  4  3  2  1]


### 7. Create a 4x4 matrix and extract the border elements (first/last row and first/last column).

In [20]:
a=np.random.randint(1,10,size=(4,4))
print(a)

border = np.concatenate([a[0],a[-1],a[:,0],a[:,-1]])
print(border)
border.sort()
print(border)

[[5 1 9 5]
 [1 5 5 3]
 [4 3 4 5]
 [3 8 3 7]]
[5 1 9 5 3 8 3 7 5 1 4 3 5 3 5 7]
[1 1 3 3 3 3 4 5 5 5 5 5 7 7 8 9]


### 8. Find the most frequent value in the array: `[1, 2, 3, 4, 4, 4, 5, 5, 6, 6, 6, 6, 7]`

In [22]:

arr = np.array([1,2,3,4,4,4,4,5,6,6,7,7,7,7,7,8,9,9,10,10,10])
val, count = np.unique(arr, return_counts=True)

print(val)
print(count)

index = np.argmax(count)
print(f'Most frequent value is {val[index]} with count {count[index]}')

[ 1  2  3  4  5  6  7  8  9 10]
[1 1 1 4 1 2 5 1 2 3]
Most frequent value is 7 with count 5


### 9. Create two arrays of shape (3, 4) and (4, 5) and perform matrix multiplication.

In [23]:
a=np.random.randint(1,100,size=(3,4))
b=np.random.randint(1,100,size=(4,5))

c = np.dot(a,b)
print(c)

d=np.matmul(a,b)
print(d)

[[ 9838  8687 12893 15463  5309]
 [13797 11626 13462 16312  7067]
 [13189 10662 15061 19828  5340]]
[[ 9838  8687 12893 15463  5309]
 [13797 11626 13462 16312  7067]
 [13189 10662 15061 19828  5340]]


### 10. Given a 2D array, swap two random rows and two random columns.

In [ ]:
a=np.random.randint(1,100,size=(2,2))

b=a.T
print(b)

#swap two randowm rows and two random columns
a=np.random.randint(1,100,size=(4,5))
print("Original array:")
print(a)
# Swap two random rows
print(a.shape[0])
row1, row2 = np.random.choice(a.shape[0], size=2, replace=False)
a[[row1, row2], :] = a[[row2, row1], :]
print("Array after swapping rows:")
print(a)
# Swap two random columns
col1, col2 = np.random.choice(a.shape[1], size=2, replace=False)
a[:, [col1, col2]] = a[:, [col2, col1]]
print("Array after swapping columns:")
print(a)

[[ 9  4]
 [68 81]]
Original array:
[[49 17 26 48]
 [91 15 32 73]
 [97 56 28 30]
 [78 75 17 28]
 [82 34 10 35]]
5
Array after swapping rows:
[[91 15 32 73]
 [49 17 26 48]
 [97 56 28 30]
 [78 75 17 28]
 [82 34 10 35]]
Array after swapping columns:
[[73 15 32 91]
 [48 17 26 49]
 [30 56 28 97]
 [28 75 17 78]
 [35 34 10 82]]


### 11. Create a 10x10 array with random integers from 1 to 100. Find all rows where the sum of elements is greater than 500.

In [28]:
a = np.random.randint(1, 100, size=(10,10))

print(a[np.sum(a, axis=1) > 500])  # Rows where sum is greater than 500


[[31 91 65 51 36 80 70 57 80 88]
 [96 67 75 67 55 51 82 58 15 29]
 [29 46 94 88 85 70 49 59 47 55]
 [70 36 67 83 32  4 78 81 91 81]]


### 12. Compute the Euclidean distance between two arrays: `a = [1, 2, 3]` and `b = [4, 5, 6]`

In [29]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])

c = np.linalg.norm(a - b)
print(c)


11.180339887498949
